title: Alessandro Sebastianelli
description: Ph.D. student at University of Sannio and ESA under OSIP contract
show_downloads: false

theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-seo-tag

title: Alessandro Sebastianelli