title: Alessandro Sebastianelli
description: Ph.D. student at University of Sannio and ESA under OSIP contract
email: alessandro.sebastianelli@gmail.com
show_downloads: false

theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-seo-tag